export const FETCH_WATCHLATER_SUCCESS = "FETCH_WATCHLATER_SUCCESS";
export const FETCH_WATCHLATER_REQUEST = "FETCH_WATCHLATER_REQUEST";
export const FETCH_WATCHLATER_FAILURE = "FETCH_WATCHLATER_FAILURE";
